[package]
name = "dxp-css-builder"
version = "0.1.1"
edition = "2021"

[[bin]]
name = "css-builder"

[workspace]

[dependencies]
clap = { version =  "^4.5.7", features = ["derive"]}
lightningcss = { version = "1.0.0-alpha.57", features = ["bundler"] }
